# Generated by Django 2.1.7 on 2019-05-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwh_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='registratrion_plate',
            new_name='registration_plate',
        ),
    ]
